//import { PartialType } from '@nestjs/mapped-types'; Generated by Nest, IDK
//import { CreateUserDto } from './create-user.dto'; IDK
import { IsNotEmpty, IsEmail, IsString, IsBoolean, IsOptional } from "class-validator";

export class UpdateUserDto {
    @IsOptional()
    @IsNotEmpty()
    @IsString()
    first_name: string;

    @IsOptional()
    @IsNotEmpty()
    @IsString()
    last_name: string;

    @IsOptional()
    @IsNotEmpty()
    @IsEmail()
    email: string;

    @IsOptional()
    @IsNotEmpty()
    @IsString()
    tax_code: string;

    @IsOptional()
    @IsNotEmpty()
    @IsString()
    password: string;

    @IsOptional()
    @IsNotEmpty()
    @IsBoolean()
    family_member: boolean;
}
